/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#b4b5b9",
        "on-tertiary-fixed": "#281900",
        "outline": "#899483",
        "on-primary-fixed-variant": "#00530b",
        "on-tertiary-container": "#3a2600",
        "on-primary": "#003a05",
        "on-background": "#e2e2e5",
        "surface-bright": "#37393b",
        "on-surface": "#e2e2e5",
        "on-tertiary": "#432c00",
        "inverse-surface": "#e2e2e5",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#604100",
        "on-secondary": "#2e3034",
        "surface-dim": "#121416",
        "on-surface-variant": "#becab7",
        "secondary": "#c5c6cb",
        "tertiary-fixed-dim": "#ffba38",
        "surface-tint": "#77dd6d",
        "secondary-fixed-dim": "#c5c6cb",
        "primary": "#77dd6d",
        "surface-variant": "#333537",
        "primary-fixed-dim": "#77dd6d",
        "tertiary": "#ffba38",
        "inverse-primary": "#006e12",
        "primary-container": "#3fa43d",
        "inverse-on-surface": "#2f3133",
        "background": "#121416",
        "surface-container-high": "#282a2c",
        "surface-container-highest": "#333537",
        "surface": "#121416",
        "on-error": "#690005",
        "surface-container-lowest": "#0c0e10",
        "primary-fixed": "#92fa86",
        "on-secondary-fixed-variant": "#45474b",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#e2e2e7",
        "on-primary-fixed": "#002202",
        "error-container": "#93000a",
        "on-primary-container": "#003204",
        "tertiary-fixed": "#ffdeac",
        "tertiary-container": "#c08600",
        "on-secondary-fixed": "#191c1f",
        "secondary-container": "#45474b",
        "surface-container": "#1e2022",
        "surface-container-low": "#1a1c1e",
        "outline-variant": "#3f4a3b"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
